name: Node.js CI

on: [pull_request]

jobs:
  buildlinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn audit
      - run: yarn
      - run: yarn lint:check
      - run: yarn style:check
      - run: yarn test
